### ISSUE TITLE
about est[2]

### ISSUE THREAD

**Issue by shenbuguanni** [echocatzh/GFTNN#2]
hi,thanks your woks, I would like to ask what's the est[2]? it used to calculate mes loss with real_t and imag_t, So, I think it is reasonable to ues est[1], I don't know what the difference is between the est[1] and est[2]

**Comment by echocatzh** [comment]
Thanks for yours attention.
est 2 is a  vad masked version of est 1, so it also has a vad judgement loss “ce”.

You can email me at shmzhang@npu-aslp.org for quick response.
