### ISSUE TITLE
Question about training target

### ISSUE THREAD

**Issue by l6chen** [echocatzh/GFTNN#3]
Hi, thanks to your work! According to your paper, the outputs of the GCCRN are the real and image part of estimated STFT features. Here I have a question that do you just use the outputs of last Dense layer to calculate loss and reconstruct signal, or use them to calculate a cIRM applied to input later, as in the original work of GCCRN?
Thanks again!

**Comment by echocatzh** [comment]
All the mentioned CRN-based models were trained by mapping, not masking.

**Comment by l6chen** [comment]
which means there 's no activation function after the last Linear, since the range of real and image part of STFT is (-∞, +∞)?

**Comment by echocatzh** [comment]
The values would be in a reasonable range. Actually, in our experiments, "mapping" works better than "masking".

**Comment by l6chen** [comment]
Ok, thanks.
